<?php

namespace Database\Seeders;

use Faker\Factory as Faker;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use JsonException;
use Random\RandomException;

class ProductSeeder extends Seeder
{
    /**
     * @throws JsonException
     * @throws RandomException
     */
    public function run(): void
    {
        $fakerEn = Faker::create();

        $product_name_en = [
            'Basbousa with Pistachio',
            'Chocolate Cake',
            'Kunafa with Cream',
            'Maamoul with Dates',
            'Baklava Assortment',
            'Cheesecake',
            'Mango Tart',
            'Chocolate Mousse',
            'Fruit Salad',
            'Oreo Cheesecake',
            'Luxury Sofa Set',
            'Modern Dining Table',
            'Ergonomic Office Chair',
            'Wooden Coffee Table',
            'Classic Bookshelf',
            'Queen Size Bed',
            'Elegant Wardrobe',
            'Leather Recliner',
            'Minimalist TV Stand',
            'Outdoor Patio Set',
            'Silk Evening Gown',
            'Casual Denim Jacket',
            'Wool Winter Coat',
            'Leather Handbag',
            'Designer Sunglasses',
            'Formal Tuxedo',
            'Summer Maxi Dress',
            'Slim Fit Jeans',
            'Classic Trench Coat',
            'Luxury Silk Scarf',
            'Sparkling Water',
            'Cold Brew Coffee',
            'Green Tea',
            'Fresh Orange Juice',
            'Herbal Infusion',
            'Classic Lemonade',
            'Ginger Ale',
            'Coconut Water',
            'Pomegranate Juice',
            'Organic Almond Milk',
            'Cotton T-Shirt',
            'Classic Hoodie',
            'Formal Shirt',
            'Sportswear Set',
            'Summer Shorts',
            'Winter Sweater',
            'Casual Dress',
            'Tailored Blazer',
            'Yoga Pants',
            'Linen Pants',
            'Luxury Gold Watch',
            'Smart Fitness Tracker',
            'Classic Leather Strap Watch',
            'Diving Watch',
            'Chronograph Watch',
            'Digital Sports Watch',
            'Minimalist Wristwatch',
            'Designer Watch with Diamond Accents',
            'Automatic Watch',
            'Vintage Pocket Watch'

        ];
        $product_name_ar = [
            'بسبوسة بالفستق',
            'كيك بالشوكولاتة',
            'كنافة بالقشطة',
            'معمول بالتمر',
            'تشكيلة بقلاوة',
            'تشيز كيك',
            'تارت المانجو',
            'موس الشوكولاتة',
            'سلطة الفواكه',
            'تشيز كيك بالأوريو',
            'مجموعة كنب فاخرة',
            'طاولة طعام عصرية',
            'كرسي مكتب مريح',
            'طاولة قهوة خشبية',
            'رف كتب كلاسيكي',
            'سرير بحجم كوين',
            'خزانة أنيقة',
            'كرسي استرخاء جلدي',
            'وحدة تلفاز بسيطة',
            'مجموعة فناء خارجي',
            'فستان سهرة حريري',
            'سترة جينز كاجوال',
            'معطف شتوي صوفي',
            'حقيبة يد جلدية',
            'نظارات شمسية مصممة',
            'بدلة رسمية',
            'فستان ماكسي صيفي',
            'جينز بقصة ضيقة',
            'معطف ترنش كلاسيكي',
            'وشاح حريري فاخر',
            'ماء فوار',
            'قهوة باردة',
            'شاي أخضر',
            'عصير برتقال طازج',
            'شراب الأعشاب',
            'ليموناضة كلاسيكية',
            'مشروب الزنجبيل',
            'ماء جوز الهند',
            'عصير رمان',
            'حليب اللوز العضوي',
            'قميص قطن',
            'هودي كلاسيكي',
            'قميص رسمي',
            'مجموعة ملابس رياضية',
            'شورت صيفي',
            'كنزة شتوية',
            'فستان كاجوال',
            'بليزر مصمم خصيصًا',
            'بنطلون يوجا',
            'بنطلون كتان',
            'قميص قطن',
            'هودي كلاسيكي',
            'قميص رسمي',
            'مجموعة ملابس رياضية',
            'شورت صيفي',
            'كنزة شتوية',
            'فستان كاجوال',
            'بليزر مصمم خصيصًا',
            'بنطلون يوجا',
            'بنطلون كتان',
        ];

        $desc_en = [
            'Experience the traditional Basbousa with a modern twist, topped with the finest pistachios.',
            'Rich and moist chocolate cake with a creamy frosting.',
            'Delicious kunafa filled with rich cream, topped with a crunchy layer.',
            'Traditional Maamoul filled with sweet dates, perfect with coffee.',
            'A delightful assortment of baklava with various fillings.',
            'Creamy cheesecake with a buttery crust, perfect for dessert lovers.',
            'Fresh and tangy mango tart with a crispy base.',
            'Smooth chocolate mousse with a rich flavor.',
            'A refreshing mix of seasonal fruits, perfect for a healthy snack.',
            'Creamy cheesecake with an Oreo cookie base, a favorite for all ages.',
            'A luxurious sofa set with a modern design and high-quality fabric.',
            'A sleek dining table that comfortably seats six people.',
            'Ergonomically designed office chair for maximum comfort.',
            'Sturdy wooden coffee table with a rustic finish.',
            'Classic bookshelf with ample storage space for books and decor.',
            'Comfortable queen-size bed with a sturdy frame.',
            'Elegant wardrobe with multiple compartments and a modern finish.',
            'Leather recliner with adjustable features for ultimate relaxation.',
            'Minimalist TV stand with storage compartments and cable management.',
            'Outdoor patio set with durable materials and stylish design.',
            'Elegant silk evening gown with a flattering silhouette.',
            'Comfortable denim jacket with a casual design.',
            'Warm wool winter coat with a tailored fit.',
            'Stylish leather handbag with ample storage space.',
            'Designer sunglasses with UV protection.',
            'Formal tuxedo with a sharp, tailored look.',
            'Flowy summer maxi dress with a vibrant print.',
            'Slim fit jeans with a modern cut.',
            'Classic trench coat with a double-breasted design.',
            'Luxury silk scarf with a smooth finish.',
            'Refreshing sparkling water with a hint of citrus.',
            'Smooth cold brew coffee with a rich flavor.',
            'Green tea with a soothing and earthy taste.',
            'Freshly squeezed orange juice, packed with vitamin C.',
            'Herbal infusion with a blend of calming herbs.',
            'Classic lemonade made with fresh lemons.',
            'Ginger ale with a spicy kick.',
            'Coconut water with natural electrolytes.',
            'Pomegranate juice with a sweet and tangy flavor.',
            'Organic almond milk with a smooth, creamy texture.',
            'Comfortable cotton t-shirt, perfect for casual wear.',
            'Classic hoodie with a soft, warm interior.',
            'Formal shirt with a crisp, clean look.',
            'Sportswear set ideal for workouts and running.',
            'Lightweight summer shorts in a range of colors.',
            'Cozy winter sweater with a stylish design.',
            'Casual dress with a comfortable fit.',
            'Tailored blazer with a modern cut.',
            'Flexible yoga pants with a snug fit.',
            'Linen pants that are cool and breathable.',
            'Luxury gold watch with a sleek design and precision craftsmanship.',
            'Smart fitness tracker with heart rate monitoring and GPS.',
            'Classic watch with a genuine leather strap and a timeless look.',
            'Durable diving watch, water-resistant up to 200 meters.',
            'Chronograph watch with multiple dials and a sporty design.',
            'Digital sports watch with a rugged exterior and stopwatch function.',
            'Minimalist wristwatch with a simple and elegant design.',
            'Designer watch with diamond accents, perfect for special occasions.',
            'Automatic watch with self-winding movement and a transparent case back.',
            'Vintage pocket watch with intricate details and a chain.'
        ];
        
        $desc_ar = [
            'استمتع بالبسبوسة التقليدية مع لمسة عصرية، مغطاة بأطيب أنواع الفستق.',
            'كيك الشوكولاتة الغني والرطب مع كريمة مميزة.',
            'كنافة لذيذة محشوة بالقشطة الغنية ومغطاة بطبقة مقرمشة.',
            'معمول تقليدي محشو بالتمر الحلو، مثالي مع القهوة.',
            'تشكيلة شهية من البقلاوة مع حشوات متنوعة.',
            'تشيز كيك كريمي مع قاعدة من البسكويت، مثالي لعشاق الحلوى.',
            'تارت المانجو الطازج واللاذع مع قاعدة مقرمشة.',
            'موس الشوكولاتة الناعم بنكهة غنية.',
            'مزيج منعش من الفواكه الموسمية، مثالي للوجبات الخفيفة الصحية.',
            'تشيز كيك كريمي مع قاعدة من بسكويت الأوريو، مفضل لجميع الأعمار.',
            'مجموعة كنب فاخرة بتصميم عصري وقماش عالي الجودة.',
            'طاولة طعام أنيقة تتسع لستة أشخاص براحة.',
            'كرسي مكتب مصمم هندسيًا للراحة القصوى.',
            'طاولة قهوة خشبية متينة بتشطيب ريفي.',
            'رف كتب كلاسيكي يوفر مساحة تخزين واسعة للكتب والديكور.',
            'سرير بحجم كوين مريح مع إطار متين.',
            'خزانة أنيقة مع مقصورات متعددة وتشطيب عصري.',
            'كرسي استرخاء جلدي مع ميزات قابلة للتعديل للاسترخاء التام.',
            'وحدة تلفاز بسيطة مع مقصورات تخزين وإدارة الكابلات.',
            'مجموعة فناء خارجي بمواد متينة وتصميم أنيق.',
            'فستان سهرة حريري أنيق بقصة جذابة.',
            'سترة جينز مريحة بتصميم كاجوال.',
            'معطف شتوي صوفي دافئ بقصة مصممة.',
            'حقيبة يد جلدية أنيقة مع مساحة تخزين واسعة.',
            'نظارات شمسية مصممة بحماية من الأشعة فوق البنفسجية.',
            'بدلة رسمية بقصة حادة ومصممة.',
            'فستان ماكسي صيفي انسيابي بطباعة زاهية.',
            'جينز بقصة ضيقة بتصميم عصري.',
            'معطف ترنش كلاسيكي بتصميم مزدوج الصدر.',
            'وشاح حريري فاخر بتشطيب ناعم.',
            'ماء فوار منعش بنكهة الحمضيات.',
            'قهوة باردة ناعمة بنكهة غنية.',
            'شاي أخضر بنكهة مهدئة وارضية.',
            'عصير برتقال طازج مليء بفيتامين C.',
            'شراب الأعشاب بمزيج من الأعشاب المهدئة.',
            'ليموناضة كلاسيكية مصنوعة من الليمون الطازج.',
            'مشروب الزنجبيل بنكهة حارة.',
            'ماء جوز الهند مع الإلكتروليتات الطبيعية.',
            'عصير رمان بنكهة حلوة وحامضة.',
            'حليب اللوز العضوي بنسيج ناعم وكريمي.',
            'قميص قطن مريح مثالي للملابس الكاجوال.',
            'هودي كلاسيكي بداخل ناعم ودافئ.',
            'قميص رسمي بمظهر نقي ونظيف.',
            'مجموعة ملابس رياضية مثالية للتمارين والجري.',
            'شورت صيفي خفيف الوزن بألوان متنوعة.',
            'كنزة شتوية دافئة بتصميم أنيق.',
            'فستان كاجوال بملائمة مريحة.',
            'بليزر مصمم خصيصًا بقصة عصرية.',
            'بنطلون يوجا مرن بملائمة مريحة.',
            'بنطلون كتان بارد وقابل للتنفس.',
            'ساعة ذهبية فاخرة بتصميم أنيق وصناعة دقيقة.',
            'متعقب اللياقة البدنية الذكي مع مراقبة معدل ضربات القلب ونظام تحديد المواقع.',
            'ساعة كلاسيكية بحزام جلدي أصلي ومظهر خالد.',
            'ساعة غوص متينة مقاومة للماء حتى 200 متر.',
            'ساعة كرونوغراف متعددة الأوجه بتصميم رياضي.',
            'ساعة رياضية رقمية بواجهة متينة ووظيفة التوقيت.',
            'ساعة معصم بسيطة بتصميم أنيق وبسيط.',
            'ساعة مصمم بلهجات ألماسية مثالية للمناسبات الخاصة.',
            'ساعة أوتوماتيكية بحركة ذاتية التعبئة وغطاء شفاف.',
            'ساعة جيب عتيقة بتفاصيل دقيقة وسلسلة.'
        ];
        $short_desc_en = [
            'Perfect for 10-12 people.',
            'Ideal for chocolate lovers.',
            'Great for traditional dessert lovers.',
            'Perfect with a cup of coffee.',
            'A delightful treat for any occasion.',
            'Ideal for cheesecake enthusiasts.',
            'Perfect for a summer treat.',
            'A rich chocolate experience.',
            'A healthy and refreshing option.',
            'A creamy dessert for all ages.',
            'Perfect for modern living rooms.',
            'Seats up to six people comfortably.',
            'Designed for extended use.',
            'Rustic charm for your home.',
            'Great for book lovers.',
            'Comfortable and stylish.',
            'Perfect for a modern bedroom.',
            'Relax in style and comfort.',
            'Ideal for small spaces.',
            'Durable and weather-resistant.',
            'Perfect for evening events.',
            'Casual and stylish.',
            'Stay warm and fashionable.',
            'A must-have accessory.',
            'Protects your eyes in style.',
            'Ideal for formal occasions.',
            'Breezy and comfortable.',
            'A wardrobe essential.',
            'Timeless and elegant.',
            'Adds a touch of luxury.',
            'Crisp and refreshing.',
            'Perfect for a caffeine boost.',
            'A healthy, soothing drink.',
            'Packed with vitamins.',
            'Relax with a herbal blend.',
            'Cool and tangy.',
            'Spicy and refreshing.',
            'Hydrate naturally.',
            'Sweet and refreshing.',
            'Dairy-free and nutritious.',
            'Casual and comfortable.',
            'Warm and stylish.',
            'Perfect for formal occasions.',
            'Ideal for active wear.',
            'Great for summer days.',
            'Stay warm in style.',
            'Easy-going and fashionable.',
            'Smart and tailored.',
            'Flexible and comfortable.',
            'Cool and breathable.',
            'Luxury and precision.',
            'Stay fit and connected.',
            'Timeless and elegant.',
            'Perfect for diving enthusiasts.',
            'Sporty and functional.',
            'Rugged and reliable.',
            'Simple and stylish.',
            'Glamorous and luxurious.',
            'Automatic and precise.',
            'Vintage charm with modern details.'
        ];

        $short_desc_ar = [
            'تكفي 10-12 شخصًا.',
            'مثالي لمحبي الشوكولاتة.',
            'رائع لمحبي الحلوى التقليدية.',
            'مثالي مع فنجان قهوة.',
            'تشكيلة رائعة لأي مناسبة.',
            'مثالي لعشاق التشيز كيك.',
            'مثالي كحلوى صيفية.',
            'تجربة شوكولاتة غنية.',
            'خيار صحي ومنعش.',
            'حلوى كريمية لجميع الأعمار.',
            'مثالي لغرف المعيشة العصرية.',
            'يتسع لستة أشخاص براحة.',
            'مصمم للاستخدام المطول.',
            'سحر ريفي لمنزلك.',
            'مثالي لمحبي الكتب.',
            'مريح وأنيق.',
            'مثالي لغرفة نوم عصرية.',
            'استرخاء بأناقة وراحة.',
            'مثالي للمساحات الصغيرة.',
            'متين ومقاوم للعوامل الجوية.',
            'مثالي للمناسبات المسائية.',
            'كاجوال وأنيق.',
            'ابقَ دافئًا وأنيقًا.',
            'إكسسوار لا غنى عنه.',
            'تحمي عينيك بأناقة.',
            'مثالي للمناسبات الرسمية.',
            'مريح ومنعش.',
            'عنصر أساسي في خزانة الملابس.',
            'كلاسيكي وأنيق.',
            'يضيف لمسة من الفخامة.',
            'مقرمش ومنعش.',
            'مثالي لزيادة الكافيين.',
            'مشروب صحي ومهدئ.',
            'مليء بالفيتامينات.',
            'استرخِ مع مزيج الأعشاب.',
            'منعش وحامض.',
            'حار ومنعش.',
            'ترطيب طبيعي.',
            'حلو ومنعش.',
            'خالي من الألبان ومغذي.',
            'كاجوال ومريح.',
            'دافئ وأنيق.',
            'مثالي للمناسبات الرسمية.',
            'مثالي للملابس الرياضية.',
            'مثالي لأيام الصيف.',
            'ابقَ دافئًا بأناقة.',
            'غير رسمي وأنيق.',
            'أنيق ومصمم خصيصًا.',
            'مرن ومريح.',
            'بارد وقابل للتنفس.',
            'الفخامة والدقة.',
            'ابقَ لائقًا ومتصلاً.',
            'خالد وأنيق.',
            'مثالي لعشاق الغوص.',
            'رياضي ووظيفي.',
            'قوي وموثوق.',
            'بسيط وأنيق.',
            'فاخر ومترف.',
            'أوتوماتيكي ودقيق.',
            'سحر عتيق بتفاصيل عصرية.'
        ];

        for ($i = 0; $i < 150; $i++) {
            $gallery = array();
            for ($x = 0; $x < 5; $x++) {
                $gallery[] = ("products/titan_template_" . random_int(0, 71) . ".jpg");
            }

            $insert_id =  DB::table('products')->insert([
                'name' => json_encode([
                    'en' => $product_name_en[random_int(0, count($product_name_en) - 1)],
                    'ar' => $product_name_ar[random_int(0, count($product_name_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'slug' => $fakerEn->slug("2") . "-" . $i,
                'sku' =>  "PRDS" . "-" . $i,
                'description' => json_encode([
                    'en' => $desc_en[random_int(0, count($desc_en) - 1)],
                    'ar' => $desc_ar[random_int(0, count($desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'short_description' => json_encode([
                    'en' => $short_desc_en[random_int(0, count($short_desc_en) - 1)],
                    'ar' => $short_desc_ar[random_int(0, count($short_desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'image' => json_encode("products/titan_template_" . random_int(0, 71) . ".jpg", JSON_THROW_ON_ERROR),
                "gallery" => json_encode($gallery, JSON_THROW_ON_ERROR),
                "meta_title" => json_encode([
                    'en' => $product_name_en[random_int(0, count($product_name_en) - 1)],
                    'ar' => $product_name_ar[random_int(0, count($product_name_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                "og_title" => json_encode([
                    'en' => $product_name_en[random_int(0, count($product_name_en) - 1)],
                    'ar' => $product_name_ar[random_int(0, count($product_name_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                "twitter_title" => json_encode([
                    'en' => $product_name_en[random_int(0, count($product_name_en) - 1)],
                    'ar' => $product_name_ar[random_int(0, count($product_name_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                "facebook_title" => json_encode([
                    'en' => $product_name_en[random_int(0, count($product_name_en) - 1)],
                    'ar' => $product_name_ar[random_int(0, count($product_name_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'meta_description' => json_encode([
                    'en' => $short_desc_en[random_int(0, count($short_desc_en) - 1)],
                    'ar' => $short_desc_ar[random_int(0, count($short_desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'og_description' => json_encode([
                    'en' => $short_desc_en[random_int(0, count($short_desc_en) - 1)],
                    'ar' => $short_desc_ar[random_int(0, count($short_desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'twitter_description' => json_encode([
                    'en' => $short_desc_en[random_int(0, count($short_desc_en) - 1)],
                    'ar' => $short_desc_ar[random_int(0, count($short_desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'facebook_description' => json_encode([
                    'en' => $short_desc_en[random_int(0, count($short_desc_en) - 1)],
                    'ar' => $short_desc_ar[random_int(0, count($short_desc_ar) - 1)],
                ], JSON_THROW_ON_ERROR),
                'og_image' => json_encode("products/titan_template_" . random_int(0, 71) . ".jpg", JSON_THROW_ON_ERROR),
                'facebook_image' => json_encode("products/titan_template_" . random_int(0, 71) . ".jpg",
                    JSON_THROW_ON_ERROR),
                'twitter_image' => json_encode("products/titan_template_" . random_int(0, 71) . ".jpg",
                    JSON_THROW_ON_ERROR),


                'price' => $fakerEn->randomNumber(4),
                'type' => 'simple',
                'is_visible' => true,
                'manage_stock' => 1,
                'in_stock' => 1,
                'stock_qtn' => $fakerEn->randomNumber(2),
                "total_sales" =>  $fakerEn->randomNumber(2),
                'created_at' => now(),
                'updated_at' => now(),
            ]);

            for ($k = 0; $k <= 3; $k++) {

                DB::table('shop_category_products')->insert([
                    'shop_category_id' => random_int(1, 7),
                    "product_id" => $i + 1,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }
}
